apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: auth-healthcheck
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 10
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000  
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: auth-microservice-service