apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gke-l7-gxlb-api-gateway
spec:
  gatewayClassName: gke-l7-gxlb
  listeners:
  - name: http-listener
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: All