apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chat-db-deploy
      app: database
  template:
    metadata:
      labels:
        name: chat-db-deploy
        app: database
    spec:
      containers:
        - env:
            - name: CASSANDRA_CLUSTER_NAME
              value: chats_database_cluster
          image: cassandra:4.0
          name: cassandra
          ports:
            - containerPort: 9042
              hostPort: 9042
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: chat-db-volume
          resources: {}
      restartPolicy: Always
      volumes:
        - name: chat-db-volume
          persistentVolumeClaim:
            claimName: chat-db-volume
status: {}
