apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chat-firebase-apache-camel-default: "true"
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: CASSANDRA_CLUSTER_NAME
              value: book
          image: cassandra:4.0
          name: cassandra
          ports:
            - containerPort: 9042
              hostPort: 9042
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: messaging-db-volume
      restartPolicy: Always
      volumes:
        - name: messaging-db-volume
          persistentVolumeClaim:
            claimName: messaging-db-volume
status: {}
