apiVersion: v1
kind: Service
metadata:
  name: chat-db-service
  labels:
    name: chat-db-service
    app: database
spec:
  type: LoadBalancer
  ports:
      - port: 9042
        targetPort: 9042
  selector:
    name: chat-db-deploy
    app: database