apiVersion: v1
kind: Service
metadata:
  name: chat-microservice-service
  labels:
    name: chat-microservice-service
    app: microservice
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: chat-microservice
    type: microservice