apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-microservice
      type: microservice
  template:
    metadata:
      labels:
        app: chat-microservice
        type: microservice
    spec:
      containers:
        - name: chat-microservice
          image: charlyjazz/chat-microservice:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /chat/api/health/
              scheme: HTTP
              port: 9000
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /chat/api/health/
              scheme: HTTP
              port: 9000
          ports:
          - containerPort: 9000
            hostPort: 9000
            protocol: TCP
          envFrom:
          - configMapRef:
              name: chat-microservices-config
          resources: {}
