version: "3"

services:
  # Zookeper, needed for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '22181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  # Kafka, needed for auth, chat, apache camel microservices and aggregated messages consumer
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # Cassandra Database, needed for chat microservice
  cassandra:
    image: 'cassandra:4.0'
    volumes:
      - messaging_db_volume:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=book
    ports:
      - '9042:9042'
  # Postgres Authentication Database, needed for auth microservice
  auth_db:
    image: postgres
    volumes:
      - auth_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth_microservice
      POSTGRES_USER: auth_microservice
      POSTGRES_PASSWORD: auth_microservice
    ports:
      - '5433:5432'
    healthcheck:
      # The pg_isready command is a PostgreSQL utility used to check
      # the status of a PostgreSQL server and determine if it is ready
      # to accept connections. When used with the -U flag followed by a username
      # as in pg_isready -U auth_microservice, it checks whether the PostgreSQL 
      # server is ready to accept connections for the specified user.
      test: ["CMD-SHELL", "pg_isready -U auth_microservice"]
      interval: 5s
      timeout: 10s
      retries: 5
  # Aggregated messages consumer, needed for Firestore
  consumer:
    build:
      context: aggregated-messages-consumer
      dockerfile: ./Dockerfile
    environment:
      BOOSTRAP_SERVER: kafka:9092
      CONTAINER_MODE: "1"
    depends_on:
      - kafka
  # Auth microservices REST API, needed for UI clients
  auth_microservice:
    build:
      context: auth-microservice
      dockerfile: ./Dockerfile
    environment:
      PROJECT_NAME: AUTHENTICATION-MICROSERVICE
      POSTGRES_HOST: auth_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: auth_microservice
      POSTGRES_USER: auth_microservice
      POSTGRES_PASSWORD: auth_microservice
      FIRST_USER_USERNAME: charlyjazz
      FIRST_USER_PASSWORD: 123456789
      SECRET_KEY: 12345689
      ACCESS_TOKEN_EXPIRE_MINUTES: 300
      ALGORITHM: HS256
    ports:
      - '8000:8000'
    depends_on:
      auth_db:
        condition: service_healthy

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  auth_db_volume:
    driver: local
  messaging_db_volume:
    driver: local
