version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '22181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  cassandra:
    image: 'cassandra:4.0'
    volumes:
      - messaging_db_volume:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=book
    ports:
      - '9042:9042'
  auth_db:
    image: postgres
    volumes:
      - auth_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth_microservice
      POSTGRES_USER: auth_microservice
      POSTGRES_PASSWORD: auth_microservice
    ports:
      - '5433:5432'
  consumer:
    build:
      context: aggregated-messages-consumer
      dockerfile: ./Dockerfile
    environment:
      BOOSTRAP_SERVER: kafka:9092
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  auth_db_volume:
    driver: local
  messaging_db_volume:
    driver: local
