version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  cassandra:
    image: 'cassandra:4.0'
    volumes:
      - messaging_db_volume:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=book
    ports:
      - '9042:9042'
  auth_db:
    image: postgres
    volumes:
      - auth_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth_microservice
      POSTGRES_USER: auth_microservice
      POSTGRES_PASSWORD: auth_microservice
    ports:
      - '5433:5432'
  # consumer:
  #   build:
  #     context: aggregated-messages-consumer
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  auth_db_volume:
    driver: local
  messaging_db_volume:
    driver: local