apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-microservice
      type: microservice
  template:
    metadata:
      labels:
        app: auth-microservice
        type: microservice
    spec:
      containers:
          - name: auth-microservice
            image: charlyjazz/auth-microservice:latest
            imagePullPolicy: Always
            livenessProbe:
              initialDelaySeconds: 60
              httpGet:
                path: /api/health/
                scheme: HTTP
                port: 8000
            readinessProbe:
              initialDelaySeconds: 60
              httpGet:
                path: /api/health/
                scheme: HTTP
                port: 8000
            ports:
              - containerPort: 8000
                hostPort: 8000
                protocol: TCP
            envFrom:
              - configMapRef:
                  name: auth-microservice-config
            resources: {}
