apiVersion: v1
kind: Service
metadata:
  name: auth-microservice-service
  labels:
    name: auth-microservice-service
    app: microservice
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-microservice
    type: microservice