apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-microservice
  name: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-microservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chat-firebase-apache-camel-default: "true"
        io.kompose.service: auth-microservice
    spec:
      containers:
          - name: auth-microservice
            image: auth-microservice
            ports:
              - containerPort: 8000
                hostPort: 8000
                protocol: TCP
            resources: {}
            envFrom:
              - configMapRef:
                  name: auth-microservice-config
      restartPolicy: Always
status: {}
