apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  labels:
    name: auth-db-service
    app: database
spec:
  type: LoadBalancer
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    name: auth-db-deploy
    app: database