apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  labels:
    name: auth-db-service
    app: database
spec:
  type: ClusterIP
  ports:
      - port: 5432
        targetPort: 5432
  selector:
    name: auth-db-deploy
    app: database