apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregated-messages-consumer
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregated-messages-consumer
  template:
    metadata:
      labels:
        app: aggregated-messages-consumer
    spec:
      containers:
        - image: charlyjazz/amc:latest
          name: aggregated-messages-consumer
          env:
            - name: CONTAINER_MODE
              value: "1"
            - name: BOOTSTRAP_SERVER_ADDRESS
              value: kafka-service:9092
          resources: {}
          volumeMounts:
            - name: firebase-secret
              mountPath: /var/lib
              readOnly: true
      volumes:
      - name: firebase-secret
        secret:
          secretName: firebase-secret