apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-service
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka