apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    name: zookeeper-service
    app: zookeeper
spec:
  type: ClusterIP
  ports:
      - port: 2181
        targetPort: 2181
  selector:
    app: zookeeper