apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: charlyjazz/frontend-web:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: frontend-secrets
        resources: {}