"""<DESCRIPTION>

Revision ID: 82c9782a97da
Revises: d3c6204b9f3c
Create Date: 2022-08-20 19:13:19.721573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c9782a97da'
down_revision = 'd3c6204b9f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
